-- local map = vim.api.nvim_set_keymap
-- local opts = { noremap = true, silent = true }
--
-- -- Move to previous/next
-- map('n', '<A-h>', '<Cmd>BufferLineCyclePrev<CR>', opts)
-- map('n', '<A-l>', '<Cmd>BufferLineCycleNext<CR>', opts)
--
-- -- Re-order to previous/next
-- map('n', '<A-k>', '<Cmd>BufferLineMovePrev<CR>', opts)
-- map('n', '<A-j>', '<Cmd>BufferLineMoveNext<CR>', opts)
--
-- -- Close buffer
-- map('n', '<A-c>', '<Cmd>bd<CR>', opts)

return {
  -- 'akinsho/bufferline.nvim',
  -- dependencies = { 'nvim-tree/nvim-web-devicons' },
  -- config = function()
  --   local bufferline = require 'bufferline'
  --   bufferline.setup {
  --     options = {
  --       -- style_preset = bufferline.style_preset.minimal,
  --       themable = false,
  --       indicator = {
  --         style = 'underline',
  --       },
  --       tab_size = 22,
  --       diagnostics = 'nvim_lsp',
  --       diagnostics_indicator = function(count, level, diagnostics_dict, context)
  --         local icon = level:match 'error' and ' ' or ' '
  --         return ' ' .. icon .. count
  --       end,
  --       offsets = {
  --         {
  --           filetype = 'neo-tree',
  --           text = 'File tree',
  --           text_align = 'center',
  --           seperator = false,
  --         },
  --       },
  --       separator_style = 'slant',
  --     },
  --   }
  -- end,
}
